### ISSUE TITLE
Timestamp validation causing crash

### ISSUE THREAD

**Issue by champgm** [champgm/Enhanced-Microsoft-Band-Alarms#23]
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.champgm.enhancedalarm/org.champgm.enhancedalarm.timerui.TimerInputActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.matches(java.lang.String)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2790)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855)
at android.app.ActivityThread.access$900(ActivityThread.java:181)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6117)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.matches(java.lang.String)' on a null object reference
at org.champgm.enhancedalarm.util.TimestampHelper.validateTimestamp(TimestampHelper.java:47)
at org.champgm.enhancedalarm.util.TimestampHelper.validate(TimestampHelper.java:51)
at org.champgm.enhancedalarm.util.TimestampHelper.access$000(TimestampHelper.java:8)
at org.champgm.enhancedalarm.util.TimestampHelper$ParsedTimestamp.<init>(TimestampHelper.java:75)
at org.champgm.enhancedalarm.util.TimestampHelper.simplifyTimeStamp(TimestampHelper.java:43)
at org.champgm.enhancedalarm.timerui.TimerInputActivity.restoreState(TimerInputActivity.java:107)
at org.champgm.enhancedalarm.timerui.TimerInputActivity.onCreate(TimerInputActivity.java:74)
at android.app.Activity.performCreate(Activity.java:6374)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2743)
... 10 more

**Comment by champgm** [comment]
I think the lesson here, as far as I can understand it, is to NEVER catch and rethrow an exception. Catch it, and deal with it somehow, even if the solution is to show a toast that says "  ¯\_(ツ)_/¯  "
