### ISSUE TITLE
Service started without intent info?

### ISSUE THREAD

**Issue by champgm** [champgm/Enhanced-Microsoft-Band-Alarms#6]
This is a crash report that showed up on the google developer console. Investigate? 

java.lang.RuntimeException: Unable to start service org.champgm.enhancedalarm.band.BandService@2bf41114 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2913)
at android.app.ActivityThread.access$2100(ActivityThread.java:148)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1390)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5312)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
at org.champgm.enhancedalarm.band.BandService.onStartCommand(BandService.java:27)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2896)
... 9 more

**Comment by champgm** [comment]
I fixed this with an on-the-fly commit... If i see any more reports pop up I will churn out another version.
